source: .
destination: _site
exclude: ['*~']
auto: Yes

release:
  a_circus_line:            Yes # 1S
  betsy_johnson:            Yes # 1C
  okla_holmes_a:            Yes # 2S
  charles_lutwidge_dodgson: Yes # 2C
  into_the_woodstock:       No  # 3S
  gates_of_hell:            No  # 3C
  mayan_fair_lady:          No  # 4S
  ben_bitdiddle:            No  # 4C
  phantom_of_the_operator:  No  # 5S
  sheila_sunshine:          No  # 5C
  ogre_of_la_mancha:        No  # 6S
  watson:                   No  # 6C
