source: .
destination: _site
exclude: ['*~', '_blind', '_site', '_stage']

release:
  a_circus_line:            Yes # 1S
  betsy_johnson:            Yes # 1C
  okla_holmes_a:            Yes # 2S
  charles_lutwidge_dodgson: Yes # 2C
  into_the_woodstock:       Yes # 3S
  william_s_bergman:        Yes # 3C
  mayan_fair_lady:          Yes # 4S
  ben_bitdiddle:            Yes # 4C
  phantom_of_the_operator:  Yes # 5S
  sheila_sunshine:          Yes # 5C
  ogre_of_la_mancha:        Yes # 6S
  watson_2_0:               Yes # 6C

  solutions:                Yes # solutions
