source: .
destination: _site
exclude: ['*~', 'solution*', 'orig']

release:
  a_circus_line:            Yes # 1S
  betsy_johnson:            Yes # 1C
  okla_holmes_a:            Yes # 2S
  charles_lutwidge_dodgson: Yes # 2C
  into_the_woodstock:       Yes # 3S
  william_s_bergman:        Yes # 3C
  mayan_fair_lady:          Yes # 4S
  ben_bitdiddle:            No  # 4C
  phantom_of_the_operator:  No  # 5S
  sheila_sunshine:          No  # 5C
  ogre_of_la_mancha:        No  # 6S
  watson:                   No  # 6C
